### PR TITLE
Added hit rate feature #5

### PR DESCRIPTION
**Pull request by kandarppatel28**
Added a new field visitCount to db schema and increment it on each link visit, as mentioned in #5

### CODE REVIEW

**Comment by bmusuko** [comment]
LG

**Comment by kandarppatel28** [comment]
Hay @bmusuko , Its my pleasure to contribute, I request you if you can add "Hactoberfest" into your repo topic, because without it the repo is considered invalid, Thank you in advance. :)

**Comment by bmusuko** [comment]
Sorry for the late response, I've added the Hacktoberfest tag. As far as I know, we don't need any tag to be considered valid, as long as we create a pull request to any public repository CMIIW

**Comment by kandarppatel28** [comment]
Thank you @bmusuko , but unfortunately it still shows invalid repo, yes you are right, but they have recently changed their rules and regulations, you can check it out on https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by kandarppatel28** [comment]
I got it, you got a typo there, correct "hactoberfest" to "hacktoberfest", after that you will be good to go

**Comment by bmusuko** [comment]
I'm so sorry, I just copy your tag earlier lol. I've changed the label to hacktoberfest, can you confirm your PR already valid? @kandarppatel28

**Comment by kandarppatel28** [comment]
Oh, that's my bad, yes @bmusuko no the PR is valid! Thank you! Happy Hacking!!!
Any thoughts regarding the implementation of the dashboard, for displaying visit count?

**Pull request merged**
