### PR TITLE
Add facebook share icon

### PR DESCRIPTION
**Pull request by Deedone**

### CODE REVIEW

**Comment by bmusuko** [comment]
I got this error:
Destination facebook link:
https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2F11111
image
Can fix this error? @Deedone

**Comment by Deedone** [comment]
Working on fixing this.

**Comment by Deedone** [comment]
Okay, I discovered that it works, you just need to provide a really valid URL. Something like https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.google.com works.

**Comment by bmusuko** [comment]
LGTM

**Pull request merged**
